sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: KzxV64mY/ZL50LVEOXVKKwcx+EVfXEtuJpyH57yWYRaH1aY7GqRwBjAV/2VTlVk5HcROmYZy7DHJUKPMqxsNxVMBhnQUoo9Es52DcBqh89AvcQkwV+IgbggK9W765fSG+CZWCkbyEdDyD7tSJO8/MSMLRgrtuJXrdjsHQ1f6gk3u3C5bHZInplcZ3VVeNUqXd0XrZpkOtKa/b0JwrC8pYuTbWkARW5VAJWznKrqI3w2jbjA6TvVq/UlHIcKQVRm+w6Y0QDjrjjxPfG/BNrgCQ72yOlCaMbgSbOAla5LfsiwrSfVWcMLx97n7kJkHlYWMdByCf087dVBxsTOX6cEwXNpJMdVXD0nkKnd7Cwh5Ziqrcxl7ku9oo3amlXa+sqfTda/Odu60nP6vSfbKxSNpWOh4ctVZ+L+YY3ZKXZu6+fVW0gEgl7hdLIM3+rIx2etC7FxiVFp7Iya2QQ6MO3RB4Ed6/7EEuf975FeaHmtHyvNcpuxyWvRD7Dp/XzdFiT8yzYTp9lEXbZiNZcGXvK5B6T2JkjeQqUBc9LhHFVuhrfyTwdxCJSCEoGqJt32iRwEynLWRvg0GXqPTh3YTV5Jp6He+qxrBjQRXtqCedM2zN2Ji0wLUE6EMP2TBxkaK2+Ifctl66Qupor/0gKxZDN3V2tD2ZM9gVnipzTjBD1UF32M=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: lSli1QzhcO6I3Akj/kE05Gu9LZQosASVPeGZtGfKl0PN0EzO4NzZ2BSfA9bsqZzZyM8iVMKxb3tUsWD8LT83YdmyB1U7xSwjtShulU6Rt5COV57PzVd2Vo42qQX6ZVDtLlOwqVLqICALC6t+0DecusqeB4NFtFLCpkaUbQB7wdxlfotlw+4NWqYEg587QuvTYRSbEYXS8IJL4v5P8WaKxXFtPeLpv0PT7WCN/i2H4zxG/xWcxJLB6RFxvcgryymPgVsuYXU0d2rsg0zZ0V9URh/md1a/CLf+rCM8BJwcu3/+ItdDR5ncLq6sraOS69Gih+Z3d07z1BbXFsOvus8TE8rG+db34pZ71yY3rejx+ZTOKq8ZaeRCkUL09/36T3aCGbJjh9p3RSx+V1GZmEDig/LPGGc+DHh0X0HHAxLcuywitoVBqKscqJh9i/X2OT+7OTjcqX5Z0ZKF0G+ZeQtch5yQLENaXMeFXyL1K9JvI//FTDEcND5MtO+fiB3iACprsml1sVPG2fRyP7olhVqLeDbu2bQENOGKlsWMGU8AzIorqjOb2zC4fKWkg1++1XCE327Kt1vOXBnQLq1z2B/TSCuWrEDoffj3hf8OsHKqrIFYMUViMojXWEqnA0OyAUWCDv0qYroB1zkBx57UZPgXl2SDtW6/NNay17/s/rRM6pQ=
